### ISSUE TITLE
Reorganize the file structure

### ISSUE THREAD

**Issue by 1chooo** [rachitsainii/cpp-codes#62]
### Descriptions

I am very grateful for this repository and find it very interesting. However, I would like to suggest organizing the code into specific folders based on their topic. If you agree with this suggestion, I would be happy to fork the repository and provide my assistance in organizing the code. Please feel free to DM me.

BR, @1chooo

**Comment by rachitsainii** [comment]
Go ahead! Would really appreciate it!

**Comment by 1chooo** [comment]
@rachitsainii Thank you! I will clone this repository and contribute some code through my own efforts.
